FROM golang:1.18-alpine AS build
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN GOPROXY=https://mirrors.aliyun.com/goproxy/ go mod download
COPY *.go ./
RUN CGO_ENABLED=0 go build -ldflags="-extldflags=-static"
RUN ls /app

FROM knative-dev-registry.cn-hangzhou.cr.aliyuncs.com/distroless/static:nonroot 
WORKDIR /
COPY --from=build /app/secure-supply-chain-sample /secure-supply-chain-sample
EXPOSE 8080
ENTRYPOINT ["/secure-supply-chain-sample"]
